### ISSUE TITLE
this python gridtiler does not aggregate

### ISSUE THREAD

**Issue by palmajoao** [eurostat/gridtiler#14]
https://github.com/eurostat/gridtiler/blob/ea158c1381a54b38807ffe592cb742eaf06387a3/py/README.md?plain=1#L4

Thanks for suggesting this python which I was trying to turn around to build an aggregation mode of MODE instead of the default sum.
However this code, althought also tiling does not have options to aggregate, or am I missing something @jgaffuri ?

**Comment by jgaffuri** [comment]
Hi !
I could finally find some time to work on a grid tiler in Python.
See here: https://github.com/eurostat/gridtiler/tree/main/py
There is a specific function for aggregation - see the code to adapt it to your case.

**Comment by jgaffuri** [comment]
There is now a possibility to tile geotiff data: see here: https://github.com/eurostat/gridtiler/tree/main/py#tiling-gridded-raster-data
using gdal first to aggregate geotiff in different modes proposed by gdal. And then tile the aggregated tiff.
