### ISSUE TITLE
Deal with warning message

### ISSUE THREAD

**Issue by jgaffuri** [eurostat/gridtiler#5]
Make it possible that this is not shown when executing the program:
"ExperimentalWarning: Import assertions are not a stable feature of the JavaScript language."

This is because of
"import pkg from "../package.json" assert { type: "json" };"
in gridtiler.js file

**Comment by joewdavies** [comment]
Fixed in https://github.com/eurostat/gridtiler/commit/8a5d34599a6b87d394e9c72049af696a46d68da9
